services:
  - type: web
    name: primeiro-exemplo
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/primeiro-exemplo-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_OPTS
        value: "-Dserver.port=${PORT}"
      - key: DB_URL
        fromDatabase:
          name: primeiro-exemplo-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: primeiro-exemplo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: primeiro-exemplo-db
          property: password

databases:
  - name: primeiro-exemplo-db
    plan: free
    databaseName: primeiro_exemplo_db
    user: postgres
